import = ["/home/angel/.config/alacritty/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.0
normal = { family = "JetBrainsMono NF Medium" }

[window]
padding = { x = 4, y = 4}
decorations_theme_variant = "Dark"
