[theme]
theme = "native"
[theme.overrides]
idle_fg = "#abb2bf"
info_fg = "#11a8cd"
good_fg = "#a1b56c"
warning_fg = "#f7ca88"
critical_fg = "#ab4642"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:35,rot_interval:0.5) $play |} "
player = ["spotify"]
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "net"
device = "wg0"
format = " $icon $speed_down.eng(prefix:K)↓ $speed_up.eng(prefix:K)↑ "
missing_format = ""

[[block]]
block = "net"
device = "wlan0"
format = " $icon $signal_strength $speed_down.eng(prefix:K)↓ $speed_up.eng(prefix:K)↑ "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
interval = 5
merge_with_next = true

[[block]]
block = "temperature"
interval = 10
chip = "coretemp-isa-0000"
format = "$average $max"

[[block]]
block = "amd_gpu"
merge_with_next = true

[[block]]
block = "temperature"
interval = 10
chip = "amdgpu-pci-0300"
format = "$average $max"

[[block]]
block = "sound"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %I:%M %p')"
