[theme]
theme = "native"
[theme.overrides]
idle_fg = "#abb2bf"
info_fg = "#11a8cd"
good_fg = "#a1b56c"
warning_fg = "#f7ca88"
critical_fg = "#ab4642"

[icons]
icons = "none"
[icons.overrides]
music = "\U000f075a" # nf-md-music
music_next = "\U000f04ad" # nf-md-skip_next
music_pause = "\U000f03e4" # nf-md-pause
music_play = "\U000f040a" # nf-md-play
music_prev = "\U000f04ae" # nf-md-skip_previous


[[block]]
block = "music"
format = " $icon {$combo.str(max_w:40,rot_interval:0.5) $play |} "
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "net"
device = "oracle"
format = " $icon $speed_down.eng(prefix:K)↓ $speed_up.eng(prefix:K)↑ "
missing_format = ""

[[block]]
block = "net"
format = " $icon $speed_down.eng(prefix:K)↓ $speed_up.eng(prefix:K)↑ "
inactive_format = " $icon x"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $available "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
interval = 5
merge_with_next = true

[[block]]
block = "temperature"
interval = 10
chip = "coretemp-isa-0000"
format = "$average $max "

[[block]]
block = "amd_gpu"
merge_with_next = true

[[block]]
block = "temperature"
interval = 10
chip = "amdgpu-pci-0300"
format = "$average $max "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $timestamp.datetime(f:'%a %d/%m %I:%M %p')"
