let mapleader=' '

call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
" Make sure you use single quotes

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'shumphrey/fugitive-gitlab.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'sheerun/vim-polyglot'
Plug 'dense-analysis/ale'
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'voldikss/vim-floaterm'
Plug 'preservim/nerdtree'
Plug 'chriskempson/base16-vim'
Plug 'jasonccox/vim-wayland-clipboard'

" Initialize plugin system
" - Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()

set termguicolors
set background=dark
colorscheme base16-tomorrow-night
" hi Normal guibg=NONE ctermbg=NONE

set noshowmode
set mouse=a
set breakindent
set smartindent
set ignorecase
set smartcase
set completeopt=menu,menuone,noselect
set clipboard=unnamedplus
set tabstop=2
set expandtab
set ruler
set number
set relativenumber
set showcmd
set noswapfile
set nowrap
set hidden
set incsearch
set scrolloff=5
set wildmenu
set wildoptions=pum,fuzzy
set wildignore+=*/.git/*,*/tmp/*,*.swp,*/node_module/*
set encoding=utf-8
set fileencoding=utf-8
set nobackup
set nowritebackup
" Having longer updatetime (default is 4000 ms = 4s) leads to noticeable
" delays and poor user experience
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved
set signcolumn=yes

" Show whitespace chars
set listchars=lead:.,eol:↲,tab:»_,extends:›,precedes:‹,trail:•

" Fixes a weird kitty issue displaying control codes when using devicons
" https://github.com/ryanoasis/vim-devicons/issues/266
set t_RV=

" Use a line cursor when in insert mode and block in other modes
let &t_SI="\e[6 q"
let &t_EI="\e[2 q"

" Start NERDTree when Vim starts with a directory argument.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif

let g:lightline = {'colorscheme': 'Tomorrow_Night'}

let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_infos': 'lightline#ale#infos',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }

let g:lightline.component_type = {
      \     'linter_checking': 'right',
      \     'linter_infos': 'right',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'right',
      \ }

let g:lightline.component_function = {  'gitbranch': 'FugitiveHead' }

let g:lightline.active = {
      \ 'left' : [ [ 'mode', 'paste' ],
      \            [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \ 'right': [ [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_infos', 'linter_ok' ],
      \            [ 'lineinfo' ],
      \            [ 'percent' ],
      \            [ 'fileformat', 'fileencoding', 'filetype'] ] }

" easier normal mode and consistent with forward/backward repeat moves
noremap , :
noremap : ,

" To be consistent with D and C
nnoremap Y y$

" Easy ESCape?
inoremap jk <ESC>
inoremap kj <ESC>

" Center cursor
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap * *zzzv
nnoremap # #zzzv

" Leave the cursor in place when joining lines
nnoremap J mzJ`z

" Copy/paste wayland
nmap <leader>y "+y
xmap <leader>y "+y
nmap <leader>p "+p
xmap <leader>p "+p

" Do not overwrite previous yank
nnoremap <leader>d "_d
vnoremap <leader>d "_d

" Open NERDTree
nnoremap <silent> <leader>n :NERDTreeToggle<CR>

" Delete current buffer
nnoremap <silent> <leader>bd :bdelete<CR>

" Move to window using the <ctrl> hjkl keys
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Source vimrc
nnoremap <leader>r :source ~/.vim/vimrc<CR>

" Open lazygit in a floating window
nnoremap <silent> <leader>gg :<C-u>FloatermNew --width=0.9 --height=0.9 lazygit<CR>

" FZF search
nnoremap <silent> <leader><Space> :Buffers<CR>
nnoremap <silent> <leader>sf :Files<CR>
nnoremap <silent> <leader>/ :BLines<CR>
nnoremap <silent> <leader>sg :GFiles<CR>
nnoremap <silent> <leader>sr :RG<CR>

" Save buffer
nnoremap <silent> <C-s> <Cmd>w<CR><ESC>
inoremap <silent> <C-s> <Cmd>w<CR><ESC>
vnoremap <silent> <C-s> <Cmd>w<CR><ESC>

" Move lines up/down
nnoremap <silent> <A-j> :m .+1<CR>==
nnoremap <silent> <A-k> :m .-2<CR>==
inoremap <silent> <A-j> <ESC>:m .+1<CR>==gi
inoremap <silent> <A-k> <ESC>:m .-2<CR>==gi
vnoremap <silent> <A-j> :m '>+1<CR>gv=gv
vnoremap <silent> <A-k> :m '<-2<CR>gv=gv

" Close preview window
nnoremap <silent> <leader>p :pc<CR>

" Quickfix
nnoremap <silent> <leader>qo :copen<CR>
nnoremap <silent> <leader>qc :cclose<CR>
nnoremap <silent> <leader>j :cn<CR>
nnoremap <silent> <leader>k :cp<CR>

" Toggle highlight column at cursor
nnoremap <silent> <leader>hc :set cursorcolumn!<CR>

" ALE
let g:ale_fix_on_save = 1
let g:ale_warn_about_trailing_whitespace = 0
let g:ale_linters_explicit = 1
let g:ale_set_balloons = 1
let g:ale_floating_preview = 1
let g:ale_hover_cursor = 0
let g:ale_completion_enabled = 1
set omnifunc=ale#completion#OmniFunc

let g:ale_linters = {
      \  "typescript": [ "eslint", "tsserver" ],
      \  "typescriptreact": [ "eslint", "tsserver" ],
      \}

let g:ale_fixers = {
      \  "typescript": [ "prettier", "eslint" ],
      \  "typescriptreact": [ "prettier", "eslint" ],
      \}

nnoremap <silent> gd :ALEGoToDefinition<CR>
nnoremap <silent> gr :ALEFindReferences<CR>
nmap <silent> <leader>aj <Plug>(ale_next_wrap)
nmap <silent> <leader>ak <Plug>(ale_previous_wrap)
nnoremap <silent> <leader>ar :ALERename<CR>
vnoremap <silent> <leader>ar :ALERename<CR>
nnoremap <silent> <nowait> <leader>ac :ALECodeAction<CR>
vnoremap <silent> <nowait> <leader>ac :ALECodeAction<CR>
nnoremap <silent> K :ALEHover<CR>
imap <C-Space> <Plug>(ale_complete)
nnoremap <silent> <leader>aq :ALEPopulateQuickfix<CR>
nnoremap <silent> [d <cmd>ALEPreviousWrap<CR>
nnoremap <silent> [d <cmd>ALENextWrap<CR>

